# Generated by Django 3.0.6 on 2020-06-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='text',
            field=models.CharField(default='0000000', max_length=300),
        ),
    ]
