# Generated by Django 3.0.6 on 2020-09-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_chatbot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatBot',
            new_name='ChatBotModel',
        ),
    ]
